### ISSUE TITLE
PDF font

### ISSUE THREAD

**Issue by peppicus** [jadsonbr/pyreport#10]
When the library generate output, in rtf format all work fine, but in pdf format i can't have the same font, it seems to use only one type of font i don't know wich font

**Comment by peppicus** [comment]
[output.zip](https://github.com/jadsonbr/pyreport/files/917140/output.zip)

**Comment by jadsonbr** [comment]
If you are running on linux and are using some Windows source, you will need to install these fonts on Linux.

The source to be used in the output is the same one defined in the confection of the report

```l
sudo apt-get install ttf-mscorefonts-installer
```

**Comment by peppicus** [comment]
Yes, i'm running on linux, but i used the same source for each couple of report, so if I should install the fonts why it seems work for RTF file and not for PDF one?

**Comment by peppicus** [comment]
[MyReports.zip](https://github.com/jadsonbr/pyreport/files/918658/MyReports.zip)

**Comment by peppicus** [comment]
anyway I've installed the fonts, as you required, but i get the same problem.

**Comment by jadsonbr** [comment]
I tried again here and got the expected result.
The fonts are the same.

[examples.tar.gz](https://github.com/jadsonbr/pyreport/files/944334/examples.tar.gz)

**Comment by peppicus** [comment]
ok, try this:
unzip the file and execute "**python jreport.py**"

[report.zip](https://github.com/jadsonbr/pyreport/files/946171/report.zip)

**Comment by jadsonbr** [comment]
My Skype to talk about your problem:

     jbr-solucoes

**Comment by peppicus** [comment]
my skype account is **peppicus70**, i asked for your friendship

**Comment by jadsonbr** [comment]
This will solve your problem.

http://jasperstarter.cenote.de/unicode-pdf-export.html

**Comment by jadsonbr** [comment]
If resolved please close the issue.

**Comment by peppicus** [comment]
ok, this doesn't seems a library problem so I think it's right close the issue.
