### ISSUE TITLE
Unable to load driver / Exception in thread "main"

### ISSUE THREAD

**Issue by InUrSys** [jadsonbr/pyreport#16]
Hi/Ola, first thank you for the time you are taking to  answer my issue.
So was trying to use, jasperpy in the program im building so I followed your tutorial and I manage to build the hello world report.
So I wanted to try with my database(postgres), and I keep getting the following error : 
`Unable to load driver: org.postgresql.Driver` 
this is the processing function I used:
`def processing_DB():
    input_file = os.path.dirname(os.path.abspath(__file__))+'/examples/saidas.jasper'
    output = os.path.dirname(os.path.abspath(__file__)) + '/examples'    
    con={
        'driver': 'postgres',
        'username': 'postgres',
        'password': 'postgres',
        'host': 'local',
        'database': 'DBToGo',
        'schema': 'public',
        'port': '5432'   
        }
    
    jasper = jasperpy.JasperPy()
    jasper.process(input_file= input_file, 
                   output_file= output, 
                   format_list= ["pdf","rtf"], 
                   db_connection= con,
                   locale='pt_BR'
                   )
    print("Done!")    `

and the error was still there, so I tried using command line:

`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyjasper/jasperstarter/bin/jasperstarter --locale pt_BR process "/Users/mruserpleasedontkillme/Documents/workspace/theProject/Reports/examples/saidas.jasper" -o "/Users/mruserpleasedontkillme/Documents/workspace/Teaching/Reports/examples" -f pdf rtf -t postgres -u postgres -p postgres -H local -n DBToGo --db-port 5432`

and the error was still there, so I tried using different approaches so i tried:
`/Users/mruserpleasedontkillme/Downloads/jasperstarter/bin/jasperstarter --locale pt_BR process "/Users/mruserpleasedontkillme/Documents/workspace/theProject/Reports/examples/saidas.jasper" -o "/Users/mruserpleasedontkillme/Documents/workspace/theProject/Reports/examples" -f pdf rtf -t generic --db-url jdbc:postgresql://localhost/DBToGo --db-driver org.postgresql.Driver  -u postgres -p postgres -H local -n DBToGo --db-port 5432`

and got a different erro this time:
`Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:72)
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:62)
	at de.cenote.tools.classpath.ApplicationClasspath.addJars(ApplicationClasspath.java:127)
	at de.cenote.tools.classpath.ApplicationClasspath.addJarsRelative(ApplicationClasspath.java:142)
	at de.cenote.jasperstarter.App.processReport(App.java:169)
	at de.cenote.jasperstarter.App.main(App.java:102)`

And again thanks for your time.

**Comment by jadsonbr** [comment]
Hello,
First of all thank you for using our library.

To connect to the database you must download the JDBC jar from the respective database.
Look here [Link](https://github.com/jadsonbr/pyreport#optional)

Then you will have to put the downloaded .jar in the jdbc folder
See more here [Link]( https://github.com/jadsonbr/pyreport#note)

Or you can put the jar in another directory and tell it where it is via the resources
See more here [Link](https://github.com/jadsonbr/pyreport#working-with-resources-i18n-resource-bundles-icons-or-images)

**Comment by InUrSys** [comment]
hi/ola, I tried doing that too and I keep getting the same error:

> Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
> 	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:72)
> 	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:62)
> 	at de.cenote.tools.classpath.ApplicationClasspath.addJars(ApplicationClasspath.java:127)
> 	at de.cenote.tools.classpath.ApplicationClasspath.addJarsRelative(ApplicationClasspath.java:142)
> 	at de.cenote.jasperstarter.App.processReport(App.java:169)
> 	at de.cenote.jasperstarter.App.main(App.java:102)

can you show me an example? probably im doing something wrong when I try using 

```
def processing_DB():
    input_file = os.path.dirname(os.path.abspath(__file__))+'/examples/saidas.jasper'
    output = os.path.dirname(os.path.abspath(__file__)) + '/examples/'    
    con={
        'driver': 'postgres',
        'username': 'postgres',
        'password': 'postgres',
        'host': 'local',
        'database': 'DBToGo',
        'schema': 'public',
        'port': '5432'   
        }
    
    jasper = jasperpy.JasperPy()
    jasper.process(input_file= input_file, 
                   output_file= output, 
                   format_list= ["pdf","rtf"], 
                   parameters={},
                   db_connection= con,
                   locale='pt_BR',
                   resource= '/Users/mruserpleasedontkillme/Downloads/pyreport-master/pyjasper/jasperstarter/jdbc/postgresql-42.1.4.jre7.jar'
                   )
    print("Done!")
```

I get the error: 
> resource= '/Users/mruserpleasedontkillme/Downloads/pyreport-master/pyjasper/jasperstarter/jdbc/postgresql-42.1.4.jre7.jar'
> TypeError: process() got an unexpected keyword argument 'resource'

so when go to jasperpy.py file the process method dosent take recourse as an argument these is  definition of process:

   ```
 def process(self, input_file, output_file=False, format_list=['pdf'],
                parameters={}, db_connection={}, locale='pt_BR'):

```

**Comment by jadsonbr** [comment]
Please take the following steps and try again.
The version you are using is 0.1.7 that does not yet have this feature.
I will soon make available the version that is in master in pip as version 0.1.8.

```bash
pip uninstall pyreportjasper
cd ~/Downloads/
git clone git@github.com:jadsonbr/pyreport.git 
cd pyreport/
python setup.py install
```

**Comment by InUrSys** [comment]
hi, so Followed your steps and everything but I keep getting the same error

```
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:72)
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:62)
	at de.cenote.jasperstarter.App.processReport(App.java:196)
	at de.cenote.jasperstarter.App.main(App.java:102)
```

so searched on the cento.issues it looks likes, the problem its with jaspersarter, here is the someone with the same problem as mine https://cenote-issues.atlassian.net/browse/JAS-98?jql=project%20%3D%20JAS%20AND%20fixVersion%20%3D%20future_java9

**Comment by jadsonbr** [comment]
Run these commands and show us the result please

```bash
java -version
javac -version
python --version
```
The most suitable JDBC drive is this [Driver JDBC PostgreSQL](https://jdbc.postgresql.org/download/postgresql-42.1.4.jar)

**Comment by InUrSys** [comment]
> IN-2:~ mruserpleasedontkillme$ java -version
> java version "9"
> Java(TM) SE Runtime Environment (build 9+181)
> Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
> IN-2:~ mruserpleasedontkillme$ javac -version
> javac 9
> IN-2:~ mruserpleasedontkillme$ python --version
> Python 2.7.10
> IN-2:~ mruserpleasedontkillme$ python3 --version
> Python 3.6.1

yes I tried with all and nom of them worked:
> postgresql-8.0-325.jdbc2.jar
> postgresql-8.1-415.jdbc2ee.jar
> postgresql-8.1-415.jdbc3.jar
> postgresql-8.2-512.jdbc2ee.jar
> postgresql-9.4-1202.jdbc41.jar
> postgresql-42.1.4.jar

**Comment by jadsonbr** [comment]
I will conduct a test here.
But what I think is a particularity of Java 9

As soon as I test, I'll post the results here

https://github.com/jadsonbr/pyreport#requirements

**Comment by InUrSys** [comment]
ok, so I can try uninstalling java9 and try an older version?

**Comment by jadsonbr** [comment]
Yes

**Comment by InUrSys** [comment]
so I removed java completely from my machine so what version do you advise me? to use

**Comment by InUrSys** [comment]
Finally, found the problem, its the java 9.
so I removed java 9 and installed java version "1.8.0_151"
```
java -version 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
everything worked perfectly thank you for your time and your awesome lib
