### ISSUE TITLE
Proposed fix to AttributeError: 'module' object has no attribute 'JasperPy'

### ISSUE THREAD

**Issue by pspiteri** [jadsonbr/pyreport#25]
Hi. Thanks for locking this together. I got stuck with a AttributeError: 'module' object has no attribute 'JasperPy' error and corrected it with using 'from pyjasper import jasperpy' and jasper = jasperpy.JasperPy() instead. Did you want to take a quick look if this is an improvement on your currently documented approach? Thanks again.

**Comment by jadsonbr** [comment]
Usually this problem occurs in windows.
You can try to use it as follows.

```python
from pyjasper.jasperpy import JasperPy

jasper = JasperPy()
```

**Comment by jadsonbr** [comment]
It was resolved, please close the issue
