### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by ShaheedHaque** [jadsonbr/pyreport#27]
The [exception handling](https://github.com/jadsonbr/pyreport/blob/cc7c079448d87155a6b0816951a30908bfcde1c2/pyjasper/jasperpy.py#L189) in jasperpy.py is not compatible with Python3, where there is no "e.message". The line should perhaps be changed to look like this:
```
                logger.exception(str(e))
```
That would also be safe on Python2. I'd be happy to submit a PR if required?

**Comment by jadsonbr** [comment]
Thanks!
