### ISSUE TITLE
 jasper.process error

### ISSUE THREAD

**Issue by peppicus** [jadsonbr/pyreport#7]
Hi, i'm trying to enjoy with your package, but i'm receiving this error:

File "jreport.py", line 13, in processing
    jasper.process(input_file, output=output, format_list=["pdf", "rtf"])
TypeError: process() got an unexpected keyword argument 'output'

where
**input_file** is /home/gtraficante/JaspersoftWorkspace/MyReports/hello_world.jasper (it exists)
**output** is /home/gtraficante/JaspersoftWorkspace/MyReports/output (it exists)

this is the jreport.py content:

```
#sudo pip install pyreportjasper
import os
import pyjasper
from pyjasper import JasperPy

def processing(nomeFile):
    input_file = '/home/gtraficante/JaspersoftWorkspace/MyReports/'+nomeFile
    print(input_file)
    output = '/home/gtraficante/JaspersoftWorkspace/MyReports/output'
    print(output)
    jasper = pyjasper.JasperPy()
    print(jasper)
    jasper.process(input_file, output=output, format_list=["pdf", "rtf"])
    print('FINITO!')

def listing_parameters(nomeFile):
    input_file = '/home/gtraficante/JaspersoftWorkspace/MyReports/'+nomeFile
    jasper = pyjasper.JasperPy()
    output = jasper.list_parameters(input_file)
    print(output)
    

    
    
#processing('hello_world.jrxml')    
processing('hello_world.jasper')

```

**Comment by mstuttgart** [comment]
@peppicus please replace `output` by `output_file` key . 

```python
jasper.process(input_file, output_file=output, format_list=["pdf", "rtf"])
```

**Comment by peppicus** [comment]
ok :-)
now i'm receiving this:


File "jreport.py", line 12, in processing
    jasper.process(input_file, output_file=output, format_list=["pdf", "rtf"])
TypeError: process() got an unexpected keyword argument 'format_list'

**Comment by mstuttgart** [comment]
Do you install from `pip`? This error not happening in last version from this repository. I believe that `pip` package in not updated.

**Comment by peppicus** [comment]
i've installed just few minute ago
pyreportjasper (0.1.3)

**Comment by mstuttgart** [comment]
See this https://pypi.python.org/pypi/pyreportjasper/0.1.3. 
The pip package is updated in 2016-11-24. The last update of this repository was in 2017-01-23 :) 

Install the version of this repository:

```bash
git clone git@github.com:jadsonbr/pyreport.git 
cd pyreport/
python setup.py install
```

**Comment by peppicus** [comment]
pip -V
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

pip freeze | grep pyreportjasper
pyreportjasper==0.1.3

**Comment by mstuttgart** [comment]
@peppicus This module was be refactored. This 0.1.3 version in not updated.

**Comment by peppicus** [comment]
but i've just installed by this command 

sudo pip install pyreportjasper

**Comment by mstuttgart** [comment]
@peppicus not install this package by `pip`. The version of `pyreportjasper` by `pip`package manager is not update. You need install manually from source code

**Comment by peppicus** [comment]
I'm not expert, can you help me with manual installation?

**Comment by mstuttgart** [comment]
You using Linux or Windows? I know use git commands?

**Comment by peppicus** [comment]
sorry, i'm using ubuntu 14.04

**Comment by mstuttgart** [comment]
Great! Open the terminal (Ctrl + Shift + T) and run this commands:

```bash
wget https://github.com/jadsonbr/pyreport/archive/master.zip
unzip pyreport-master.zip
cd pyreport-master
sudo python setup.py install
```
This must work :)

**Comment by peppicus** [comment]
as said before i've obtained the same version... 
pyreportjasper (0.1.3)
but the error is different

python jreport.py 
Traceback (most recent call last):
  File "jreport.py", line 4, in <module>
    from pyjasper import JasperPy
ImportError: cannot import name JasperPy

I've removed the import of JasperPy but the result is unchanged

Traceback (most recent call last):
  File "jreport.py", line 26, in <module>
    processing('hello_world.jasper')
  File "jreport.py", line 11, in processing
    jasper = pyjasper.JasperPy()
AttributeError: 'module' object has no attribute 'JasperPy'

**Comment by mstuttgart** [comment]
Yes. The author of package not update the version. Edit the `pyjasper/__init__.py` and change the version to `0.1.4`, for exemple and run the install command again.

**Comment by peppicus** [comment]
I installed ver 0.1.4

python jreport.py 
/home/gtraficante/JaspersoftWorkspace/MyReports/hello_world.jasper
/home/gtraficante/JaspersoftWorkspace/MyReports/output
Traceback (most recent call last):
  File "jreport.py", line 26, in <module>
    processing('hello_world.jasper')
  File "jreport.py", line 11, in processing
    jasper = pyjasper.JasperPy()
AttributeError: 'module' object has no attribute 'JasperPy'

**Comment by tjaol** [comment]
I tired to run on windows, doesnt works just because the slash \/ ??

**Comment by peppicus** [comment]
which / ?

**Comment by tjaol** [comment]
def processing(nomeFile):
    input_file = 'C:/Python27/'+nomeFile
    print(input_file)
    output = 'C:/Python27/output'
    print(output)
    jasper = pyjasper.JasperPy()
    print(jasper)
    jasper.process(input_file, output_file=output, format=["pdf", "rtf"])
    print('FINITO!')


C:\Users\WangY>python testjas.py
C:/Python27/hello_world.jrxml
C:/Python27/output
<pyjasper.jasperpy.JasperPy instance at 0x02FAD3C8>
FINITO!

C:\Users\tjaol>

**Comment by peppicus** [comment]
i've installed 0.1.4 version and i get 

jasper = pyjasper.JasperPy()
AttributeError: 'module' object has no attribute 'JasperPy'

maybe, you have another package version...

**Comment by mstuttgart** [comment]
@peppicus the file send to  `input_file` parameter `process` method must be a `.jrxml` file in. Not a `.jasper` file.
Do you uninstall 0.1.3 version before install "0.1.4"? I use this pakage in production enviroment and it work fine.

**Comment by peppicus** [comment]
Great!
I'm waiting for your next version.

really good work!

**Comment by jadsonbr** [comment]
Version 0.1.5 was released on pypi.
Follow the link https://pypi.python.org/pypi/pyreportjasper/0.1.5
Sorry for a delay

**Comment by mstuttgart** [comment]
Thanks @jadsonbr . We can make this release automatically using TravisCI. I will made a issue about this
