### ISSUE TITLE
Invalid resource

### ISSUE THREAD

**Issue by peppicus** [jadsonbr/pyreport#8]
i've updated the package, but it doesn't work:

/home/gtraficante/JaspersoftWorkspace/MyReports/Blank_Letter.jasper
True
True
/home/gtraficante/JaspersoftWorkspace/MyReports/output
True
<pyjasper.jasperpy.JasperPy instance at 0x7f6a27c87d40>
Traceback (most recent call last):
  File "jreport.py", line 55, in <module>
    processing('Blank_Letter.jasper')    
  File "jreport.py", line 19, in processing
    jasper.process(input_file, output_file=output, format_list=["pdf", "rtf"])
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 144, in process
    return self.execute()
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 191, in execute
    raise NameError('Invalid resource directory!')
NameError: Invalid resource directory!

the code is 

```
import os
import pyjasper
from pyjasper import jasperpy

def processing(nomeFile):
    input_file = '/home/gtraficante/JaspersoftWorkspace/MyReports/'+nomeFile
    print(input_file)
    print(os.path.isdir('/home/gtraficante/JaspersoftWorkspace/MyReports'))
    print(os.path.isfile(input_file))
    output = '/home/gtraficante/JaspersoftWorkspace/MyReports/output'
    print(output)
    print(os.path.exists(output))    
    jasper = jasperpy.JasperPy()
    print(jasper)
    jasper.process(input_file, output_file=output, format_list=["pdf", "rtf"])
    print('The End!')

processing('Blank_Letter.jasper') 


```

with the old version you sended me yesterday (0.1.4) all works fine

**Comment by mstuttgart** [comment]
The code is fine, I guess. But in my tests, I use as `input_file` a `.jrxml` file path.

**Comment by peppicus** [comment]
with jrxml i've got the same result

python jreport.py 
/home/gtraficante/JaspersoftWorkspace/MyReports/Blank_Letter.jrxml
True
True
/home/gtraficante/JaspersoftWorkspace/MyReports/output
True
<pyjasper.jasperpy.JasperPy instance at 0x7f44618dbd40>
Traceback (most recent call last):
  File "jreport.py", line 54, in <module>
    processing('Blank_Letter.jrxml')    
  File "jreport.py", line 19, in processing
    jasper.process(input_file, output_file=output, format_list=["pdf", "rtf"])
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 144, in process
    return self.execute()
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 191, in execute
    raise NameError('Invalid resource directory!')
NameError: Invalid resource directory!

**BUT with version (0.1.4) all works fine**

**Comment by jadsonbr** [comment]
```python
import os
import pyjasper
# It is not necessary to use the import below
# from pyjasper import jasperpy

def processing(nomeFile):
    input_file = '/home/gtraficante/JaspersoftWorkspace/MyReports/'+nomeFile
    print(input_file)
    print(os.path.isdir('/home/gtraficante/JaspersoftWorkspace/MyReports'))
    print(os.path.isfile(input_file))
    output = '/home/gtraficante/JaspersoftWorkspace/MyReports/output'
    print(output)
    print(os.path.exists(output))   
    jasper = jasperpy.JasperPy()
    print(jasper)
    jasper.process(
        input_file,
        output=output,
        format_list=["pdf"],
        locale='en_US'
    )
    print('The End!')

processing('Blank_Letter.jrxml')
```

**Comment by peppicus** [comment]
with (0.1.5) after modified 
**output**=output, -> **output_file**=output,

i got this error:
python jreport.py 
[...]    
jasper = jasperpy.JasperPy()
NameError: global name 'jasperpy' is not defined

So i put again this 
**from pyjasper import jasperpy**

so i got:
[...]
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 191, in execute
    raise NameError('Invalid resource directory!')

**Comment by jadsonbr** [comment]
Sorry, I've identified an error in version 0.1.5. I'm correcting it and I'm updating it

**Comment by peppicus** [comment]
with 0.1.6 all works fine.
